spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: db/changelog/master.xml
  datasource:
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASSWORD}
    url: ${POSTGRES_DB_URL}
    driver-class-name: org.postgresql.Driver

#todo CHANGE SECRET AND REMOVE TO ENV. THAT'S ONLY FOR TEST!

file-storage:
  url: http://localhost:8080/api/v1/asset/get/

#access and refresh in hours.
security:
  jwt:
    secret: amJ1eWd0aXZmdHlyY2Z5dWdpdW9ndW95Z2l1Z295dWd5dW9ndXlmdHlmdXlndXR5dWpndXlvZ3l2aXBqaWhpdWl1aGlqbmlqbg==
    access: 1
    refresh: 30

s3-aws:
  url: http://localhost:9000
  accessKey: minioroot
  secretKey: minioroot
  bucket: meme-store-bucket

springdoc:
  override-with-generic-response: false

telegram:
  bot-name: meme_st0re_bot
  bot-token: 6728196094:AAGh5uSU04zF3RkM-BCzEEbapDsnbsTTmNs
  api-url: "https://api.telegram.org/"
  file:
    info-uri: "https://api.telegram.org/bot{token}/getFile?file_id={fileId}"
    storage-uri: "https://api.telegram.org/file/bot{token}/{filePath}"

